// Lista completa de países del mundo con su emoji de bandera
// Fuente: Unicode CLDR + Wikipedia
// Formato: nombre en español, código ISO 3166-1 alpha-2, emoji

export interface Pais {
  nombre: string;
  codigo: string;
  emoji: string;
}

export const paises: Pais[] = [
  { nombre: "Afganistán", codigo: "AF", emoji: "🇦🇫" },
  { nombre: "Albania", codigo: "AL", emoji: "🇦🇱" },
  { nombre: "Alemania", codigo: "DE", emoji: "🇩🇪" },
  { nombre: "Andorra", codigo: "AD", emoji: "🇦🇩" },
  { nombre: "Angola", codigo: "AO", emoji: "🇦🇴" },
  { nombre: "Antigua y Barbuda", codigo: "AG", emoji: "🇦🇬" },
  { nombre: "Arabia Saudita", codigo: "SA", emoji: "🇸🇦" },
  { nombre: "Argelia", codigo: "DZ", emoji: "🇩🇿" },
  { nombre: "Argentina", codigo: "AR", emoji: "🇦🇷" },
  { nombre: "Armenia", codigo: "AM", emoji: "🇦🇲" },
  { nombre: "Australia", codigo: "AU", emoji: "🇦🇺" },
  { nombre: "Austria", codigo: "AT", emoji: "🇦🇹" },
  { nombre: "Azerbaiyán", codigo: "AZ", emoji: "🇦🇿" },
  { nombre: "Bahamas", codigo: "BS", emoji: "🇧🇸" },
  { nombre: "Bangladés", codigo: "BD", emoji: "🇧🇩" },
  { nombre: "Barbados", codigo: "BB", emoji: "🇧🇧" },
  { nombre: "Baréin", codigo: "BH", emoji: "🇧🇭" },
  { nombre: "Bélgica", codigo: "BE", emoji: "🇧🇪" },
  { nombre: "Belice", codigo: "BZ", emoji: "🇧🇿" },
  { nombre: "Benín", codigo: "BJ", emoji: "🇧🇯" },
  { nombre: "Bielorrusia", codigo: "BY", emoji: "🇧🇾" },
  { nombre: "Birmania", codigo: "MM", emoji: "🇲🇲" },
  { nombre: "Bolivia", codigo: "BO", emoji: "🇧🇴" },
  { nombre: "Bosnia y Herzegovina", codigo: "BA", emoji: "🇧🇦" },
  { nombre: "Botsuana", codigo: "BW", emoji: "🇧🇼" },
  { nombre: "Brasil", codigo: "BR", emoji: "🇧🇷" },
  { nombre: "Brunéi", codigo: "BN", emoji: "🇧🇳" },
  { nombre: "Bulgaria", codigo: "BG", emoji: "🇧🇬" },
  { nombre: "Burkina Faso", codigo: "BF", emoji: "🇧🇫" },
  { nombre: "Burundi", codigo: "BI", emoji: "🇧🇮" },
  { nombre: "Bután", codigo: "BT", emoji: "🇧🇹" },
  { nombre: "Cabo Verde", codigo: "CV", emoji: "🇨🇻" },
  { nombre: "Camboya", codigo: "KH", emoji: "🇰🇭" },
  { nombre: "Camerún", codigo: "CM", emoji: "🇨🇲" },
  { nombre: "Canadá", codigo: "CA", emoji: "🇨🇦" },
  { nombre: "Catar", codigo: "QA", emoji: "🇶🇦" },
  { nombre: "Chad", codigo: "TD", emoji: "🇹🇩" },
  { nombre: "Chile", codigo: "CL", emoji: "🇨🇱" },
  { nombre: "China", codigo: "CN", emoji: "🇨🇳" },
  { nombre: "Chipre", codigo: "CY", emoji: "🇨🇾" },
  { nombre: "Ciudad del Vaticano", codigo: "VA", emoji: "🇻🇦" },
  { nombre: "Colombia", codigo: "CO", emoji: "🇨🇴" },
  { nombre: "Comoras", codigo: "KM", emoji: "🇰🇲" },
  { nombre: "Corea del Norte", codigo: "KP", emoji: "🇰🇵" },
  { nombre: "Corea del Sur", codigo: "KR", emoji: "🇰🇷" },
  { nombre: "Costa de Marfil", codigo: "CI", emoji: "🇨🇮" },
  { nombre: "Costa Rica", codigo: "CR", emoji: "🇨🇷" },
  { nombre: "Croacia", codigo: "HR", emoji: "🇭🇷" },
  { nombre: "Cuba", codigo: "CU", emoji: "🇨🇺" },
  { nombre: "Dinamarca", codigo: "DK", emoji: "🇩🇰" },
  { nombre: "Dominica", codigo: "DM", emoji: "🇩🇲" },
  { nombre: "Ecuador", codigo: "EC", emoji: "🇪🇨" },
  { nombre: "Egipto", codigo: "EG", emoji: "🇪🇬" },
  { nombre: "El Salvador", codigo: "SV", emoji: "🇸🇻" },
  { nombre: "Emiratos Árabes Unidos", codigo: "AE", emoji: "🇦🇪" },
  { nombre: "Eritrea", codigo: "ER", emoji: "🇪🇷" },
  { nombre: "Eslovaquia", codigo: "SK", emoji: "🇸🇰" },
  { nombre: "Eslovenia", codigo: "SI", emoji: "🇸🇮" },
  { nombre: "España", codigo: "ES", emoji: "🇪🇸" },
  { nombre: "Estados Unidos", codigo: "US", emoji: "🇺🇸" },
  { nombre: "Estonia", codigo: "EE", emoji: "🇪🇪" },
  { nombre: "Esuatini", codigo: "SZ", emoji: "🇸🇿" },
  { nombre: "Etiopía", codigo: "ET", emoji: "🇪🇹" },
  { nombre: "Filipinas", codigo: "PH", emoji: "🇵🇭" },
  { nombre: "Finlandia", codigo: "FI", emoji: "🇫🇮" },
  { nombre: "Fiyi", codigo: "FJ", emoji: "🇫🇯" },
  { nombre: "Francia", codigo: "FR", emoji: "🇫🇷" },
  { nombre: "Gabón", codigo: "GA", emoji: "🇬🇦" },
  { nombre: "Gambia", codigo: "GM", emoji: "🇬🇲" },
  { nombre: "Georgia", codigo: "GE", emoji: "🇬🇪" },
  { nombre: "Ghana", codigo: "GH", emoji: "🇬🇭" },
  { nombre: "Granada", codigo: "GD", emoji: "🇬🇩" },
  { nombre: "Grecia", codigo: "GR", emoji: "🇬🇷" },
  { nombre: "Guatemala", codigo: "GT", emoji: "🇬🇹" },
  { nombre: "Guyana", codigo: "GY", emoji: "🇬🇾" },
  { nombre: "Guinea", codigo: "GN", emoji: "🇬🇳" },
  { nombre: "Guinea ecuatorial", codigo: "GQ", emoji: "🇬🇶" },
  { nombre: "Guinea-Bisáu", codigo: "GW", emoji: "🇬🇼" },
  { nombre: "Haití", codigo: "HT", emoji: "🇭🇹" },
  { nombre: "Honduras", codigo: "HN", emoji: "🇭🇳" },
  { nombre: "Hungría", codigo: "HU", emoji: "🇭🇺" },
  { nombre: "India", codigo: "IN", emoji: "🇮🇳" },
  { nombre: "Indonesia", codigo: "ID", emoji: "🇮🇩" },
  { nombre: "Irak", codigo: "IQ", emoji: "🇮🇶" },
  { nombre: "Irán", codigo: "IR", emoji: "🇮🇷" },
  { nombre: "Irlanda", codigo: "IE", emoji: "🇮🇪" },
  { nombre: "Islandia", codigo: "IS", emoji: "🇮🇸" },
  { nombre: "Islas Marshall", codigo: "MH", emoji: "🇲🇭" },
  { nombre: "Islas Salomón", codigo: "SB", emoji: "🇸🇧" },
  { nombre: "Israel", codigo: "IL", emoji: "🇮🇱" },
  { nombre: "Italia", codigo: "IT", emoji: "🇮🇹" },
  { nombre: "Jamaica", codigo: "JM", emoji: "🇯🇲" },
  { nombre: "Japón", codigo: "JP", emoji: "🇯🇵" },
  { nombre: "Jordania", codigo: "JO", emoji: "🇯🇴" },
  { nombre: "Kazajistán", codigo: "KZ", emoji: "🇰🇿" },
  { nombre: "Kenia", codigo: "KE", emoji: "🇰🇪" },
  { nombre: "Kirguistán", codigo: "KG", emoji: "🇰🇬" },
  { nombre: "Kiribati", codigo: "KI", emoji: "🇰🇮" },
  { nombre: "Kuwait", codigo: "KW", emoji: "🇰🇼" },
  { nombre: "Laos", codigo: "LA", emoji: "🇱🇦" },
  { nombre: "Lesoto", codigo: "LS", emoji: "🇱🇸" },
  { nombre: "Letonia", codigo: "LV", emoji: "🇱🇻" },
  { nombre: "Líbano", codigo: "LB", emoji: "🇱🇧" },
  { nombre: "Liberia", codigo: "LR", emoji: "🇱🇷" },
  { nombre: "Libia", codigo: "LY", emoji: "🇱🇾" },
  { nombre: "Liechtenstein", codigo: "LI", emoji: "🇱🇮" },
  { nombre: "Lituania", codigo: "LT", emoji: "🇱🇹" },
  { nombre: "Luxemburgo", codigo: "LU", emoji: "🇱🇺" },
  { nombre: "Madagascar", codigo: "MG", emoji: "🇲🇬" },
  { nombre: "Malasia", codigo: "MY", emoji: "🇲🇾" },
  { nombre: "Malaui", codigo: "MW", emoji: "🇲🇼" },
  { nombre: "Maldivas", codigo: "MV", emoji: "🇲🇻" },
  { nombre: "Malí", codigo: "ML", emoji: "🇲🇱" },
  { nombre: "Malta", codigo: "MT", emoji: "🇲🇹" },
  { nombre: "Marruecos", codigo: "MA", emoji: "🇲🇦" },
  { nombre: "Mauricio", codigo: "MU", emoji: "🇲🇺" },
  { nombre: "Mauritania", codigo: "MR", emoji: "🇲🇷" },
  { nombre: "México", codigo: "MX", emoji: "🇲🇽" },
  { nombre: "Micronesia", codigo: "FM", emoji: "🇫🇲" },
  { nombre: "Moldavia", codigo: "MD", emoji: "🇲🇩" },
  { nombre: "Mónaco", codigo: "MC", emoji: "🇲🇨" },
  { nombre: "Mongolia", codigo: "MN", emoji: "🇲🇳" },
  { nombre: "Montenegro", codigo: "ME", emoji: "🇲🇪" },
  { nombre: "Mozambique", codigo: "MZ", emoji: "🇲🇿" },
  { nombre: "Namibia", codigo: "NA", emoji: "🇳🇦" },
  { nombre: "Nauru", codigo: "NR", emoji: "🇳🇷" },
  { nombre: "Nepal", codigo: "NP", emoji: "🇳🇵" },
  { nombre: "Nicaragua", codigo: "NI", emoji: "🇳🇮" },
  { nombre: "Níger", codigo: "NE", emoji: "🇳🇪" },
  { nombre: "Nigeria", codigo: "NG", emoji: "🇳🇬" },
  { nombre: "Noruega", codigo: "NO", emoji: "🇳🇴" },
  { nombre: "Nueva Zelanda", codigo: "NZ", emoji: "🇳🇿" },
  { nombre: "Omán", codigo: "OM", emoji: "🇴🇲" },
  { nombre: "Países Bajos", codigo: "NL", emoji: "🇳🇱" },
  { nombre: "Pakistán", codigo: "PK", emoji: "🇵🇰" },
  { nombre: "Palaos", codigo: "PW", emoji: "🇵🇼" },
  { nombre: "Palestina", codigo: "PS", emoji: "🇵🇸" },
  { nombre: "Panamá", codigo: "PA", emoji: "🇵🇦" },
  { nombre: "Papúa Nueva Guinea", codigo: "PG", emoji: "🇵🇬" },
  { nombre: "Paraguay", codigo: "PY", emoji: "🇵🇾" },
  { nombre: "Perú", codigo: "PE", emoji: "🇵🇪" },
  { nombre: "Polonia", codigo: "PL", emoji: "🇵🇱" },
  { nombre: "Portugal", codigo: "PT", emoji: "🇵🇹" },
  { nombre: "Reino Unido", codigo: "GB", emoji: "🇬🇧" },
  { nombre: "República Centroafricana", codigo: "CF", emoji: "🇨🇫" },
  { nombre: "República Checa", codigo: "CZ", emoji: "🇨🇿" },
  { nombre: "República del Congo", codigo: "CG", emoji: "🇨🇬" },
  { nombre: "República Democrática del Congo", codigo: "CD", emoji: "🇨🇩" },
  { nombre: "República Dominicana", codigo: "DO", emoji: "🇩🇴" },
  { nombre: "Ruanda", codigo: "RW", emoji: "🇷🇼" },
  { nombre: "Rumanía", codigo: "RO", emoji: "🇷🇴" },
  { nombre: "Rusia", codigo: "RU", emoji: "🇷🇺" },
  { nombre: "Samoa", codigo: "WS", emoji: "🇼🇸" },
  { nombre: "San Cristóbal y Nieves", codigo: "KN", emoji: "🇰🇳" },
  { nombre: "San Marino", codigo: "SM", emoji: "🇸🇲" },
  { nombre: "San Vicente y las Granadinas", codigo: "VC", emoji: "🇻🇨" },
  { nombre: "Santa Lucía", codigo: "LC", emoji: "🇱🇨" },
  { nombre: "Santo Tomé y Príncipe", codigo: "ST", emoji: "🇸🇹" },
  { nombre: "Senegal", codigo: "SN", emoji: "🇸🇳" },
  { nombre: "Serbia", codigo: "RS", emoji: "🇷🇸" },
  { nombre: "Seychelles", codigo: "SC", emoji: "🇸🇨" },
  { nombre: "Sierra Leona", codigo: "SL", emoji: "🇸🇱" },
  { nombre: "Singapur", codigo: "SG", emoji: "🇸🇬" },
  { nombre: "Siria", codigo: "SY", emoji: "🇸🇾" },
  { nombre: "Somalia", codigo: "SO", emoji: "🇸🇴" },
  { nombre: "Sri Lanka", codigo: "LK", emoji: "🇱🇰" },
  { nombre: "Sudáfrica", codigo: "ZA", emoji: "🇿🇦" },
  { nombre: "Sudán", codigo: "SD", emoji: "🇸🇩" },
  { nombre: "Sudán del Sur", codigo: "SS", emoji: "🇸🇸" },
  { nombre: "Suecia", codigo: "SE", emoji: "🇸🇪" },
  { nombre: "Suiza", codigo: "CH", emoji: "🇨🇭" },
  { nombre: "Surinam", codigo: "SR", emoji: "🇸🇷" },
  { nombre: "Tailandia", codigo: "TH", emoji: "🇹🇭" },
  { nombre: "Tanzania", codigo: "TZ", emoji: "🇹🇿" },
  { nombre: "Tayikistán", codigo: "TJ", emoji: "🇹🇯" },
  { nombre: "Timor Oriental", codigo: "TL", emoji: "🇹🇱" },
  { nombre: "Togo", codigo: "TG", emoji: "🇹🇬" },
  { nombre: "Tonga", codigo: "TO", emoji: "🇹🇴" },
  { nombre: "Trinidad y Tobago", codigo: "TT", emoji: "🇹🇹" },
  { nombre: "Túnez", codigo: "TN", emoji: "🇹🇳" },
  { nombre: "Turkmenistán", codigo: "TM", emoji: "🇹🇲" },
  { nombre: "Turquía", codigo: "TR", emoji: "🇹🇷" },
  { nombre: "Tuvalu", codigo: "TV", emoji: "🇹🇻" },
  { nombre: "Ucrania", codigo: "UA", emoji: "🇺🇦" },
  { nombre: "Uganda", codigo: "UG", emoji: "🇺🇬" },
  { nombre: "Uruguay", codigo: "UY", emoji: "🇺🇾" },
  { nombre: "Uzbekistán", codigo: "UZ", emoji: "🇺🇿" },
  { nombre: "Vanuatu", codigo: "VU", emoji: "🇻🇺" },
  { nombre: "Venezuela", codigo: "VE", emoji: "🇻🇪" },
  { nombre: "Vietnam", codigo: "VN", emoji: "🇻🇳" },
  { nombre: "Yemen", codigo: "YE", emoji: "🇾🇪" },
  { nombre: "Yibuti", codigo: "DJ", emoji: "🇩🇯" },
  { nombre: "Zambia", codigo: "ZM", emoji: "🇿🇲" },
  { nombre: "Zimbabue", codigo: "ZW", emoji: "🇿🇼" },
]; 