// Lista completa de países del mundo con su emoji de bandera
// Fuente: Unicode CLDR + Wikipedia
// Formato: nombre en español, código ISO 3166-1 alpha-2, emoji

export interface Pais {
  nombre: string;
  codigo: string;
  emoji: string;
}

export const paises: Pais[] = [
  { nombre: "Afganistán", codigo: "AF", emoji: "🇦🇫" },
  { nombre: "Albania", codigo: "AL", emoji: "🇦🇱" },
  { nombre: "Alemania", codigo: "DE", emoji: "🇩🇪" },
  { nombre: "Andorra", codigo: "AD", emoji: "🇦🇩" },
  { nombre: "Angola", codigo: "AO", emoji: "🇦🇴" },
  { nombre: "Antigua y Barbuda", codigo: "AG", emoji: "🇦🇬" },
  { nombre: "Arabia Saudita", codigo: "SA", emoji: "🇸🇦" },
  { nombre: "Argelia", codigo: "DZ", emoji: "🇩🇿" },
  { nombre: "Argentina", codigo: "AR", emoji: "🇦🇷" },
  { nombre: "Armenia", codigo: "AM", emoji: "🇦🇲" },
  { nombre: "Australia", codigo: "AU", emoji: "🇦🇺" },
  { nombre: "Austria", codigo: "AT", emoji: "🇦🇹" },
  { nombre: "Azerbaiyán", codigo: "AZ", emoji: "🇦🇿" },
  { nombre: "Bahamas", codigo: "BS", emoji: "🇧🇸" },
  { nombre: "Bangladés", codigo: "BD", emoji: "🇧🇩" },
  { nombre: "Barbados", codigo: "BB", emoji: "🇧🇧" },
  { nombre: "Baréin", codigo: "BH", emoji: "🇧🇭" },
  { nombre: "Bélgica", codigo: "BE", emoji: "🇧🇪" },
  { nombre: "Belice", codigo: "BZ", emoji: "🇧🇿" },
  { nombre: "Benín", codigo: "BJ", emoji: "🇧🇯" },
  { nombre: "Bielorrusia", codigo: "BY", emoji: "🇧🇾" },
  { nombre: "Birmania", codigo: "MM", emoji: "🇲🇲" },
  { nombre: "Bolivia", codigo: "BO", emoji: "🇧🇴" },
  { nombre: "Bosnia y Herzegovina", codigo: "BA", emoji: "🇧🇦" },
  { nombre: "Botsuana", codigo: "BW", emoji: "🇧🇼" },
  { nombre: "Brasil", codigo: "BR", emoji: "🇧🇷" },
  { nombre: "Brunéi", codigo: "BN", emoji: "🇧🇳" },
  { nombre: "Bulgaria", codigo: "BG", emoji: "🇧🇬" },
  { nombre: "Burkina Faso", codigo: "BF", emoji: "🇧🇫" },
  { nombre: "Burundi", codigo: "BI", emoji: "🇧🇮" },
  { nombre: "Bután", codigo: "BT", emoji: "🇧🇹" },
  { nombre: "Cabo Verde", codigo: "CV", emoji: "🇨🇻" },
  { nombre: "Camboya", codigo: "KH", emoji: "🇰🇭" },
  { nombre: "Camerún", codigo: "CM", emoji: "🇨🇲" },
  { nombre: "Canadá", codigo: "CA", emoji: "🇨🇦" },
  { nombre: "Catar", codigo: "QA", emoji: "🇶🇦" },
  { nombre: "Chad", codigo: "TD", emoji: "🇹🇩" },
  { nombre: "Chile", codigo: "CL", emoji: "🇨🇱" },
  { nombre: "China", codigo: "CN", emoji: "🇨🇳" },
  { nombre: "Chipre", codigo: "CY", emoji: "🇨🇾" },
  { nombre: "Ciudad del Vaticano", codigo: "VA", emoji: "🇻🇦" },
  { nombre: "Colombia", codigo: "CO", emoji: "🇨🇴" },
  { nombre: "Comoras", codigo: "KM", emoji: "🇰🇲" },
  { nombre: "Corea del Norte", codigo: "KP", emoji: "🇰🇵" },
  { nombre: "Corea del Sur", codigo: "KR", emoji: "🇰🇷" },
  { nombre: "Costa de Marfil", codigo: "CI", emoji: "🇨🇮" },
  { nombre: "Costa Rica", codigo: "CR", emoji: "🇨🇷" },
  { nombre: "Croacia", codigo: "HR", emoji: "🇭🇷" },
  { nombre: "Cuba", codigo: "CU", emoji: "🇨🇺" },
  { nombre: "Dinamarca", codigo: "DK", emoji: "🇩🇰" },
  { nombre: "Dominica", codigo: "DM", emoji: "🇩🇲" },
  { nombre: "Ecuador", codigo: "EC", emoji: "🇪🇨" },
  { nombre: "Egipto", codigo: "EG", emoji: "🇪🇬" },
  { nombre: "El Salvador", codigo: "SV", emoji: "🇸🇻" },
  { nombre: "Emiratos Árabes Unidos", codigo: "AE", emoji: "🇦🇪" },
  { nombre: "Eritrea", codigo: "ER", emoji: "🇪🇷" },
  { nombre: "Eslovaquia", codigo: "SK", emoji: "🇸🇰" },
  { nombre: "Eslovenia", codigo: "SI", emoji: "🇸🇮" },
  { nombre: "España", codigo: "ES", emoji: "🇪🇸" },
  { nombre: "Estados Unidos", codigo: "US", emoji: "🇺🇸" },
  { nombre: "Estonia", codigo: "EE", emoji: "🇪🇪" },
  { nombre: "Esuatini", codigo: "SZ", emoji: "🇸🇿" },
  { nombre: "Etiopía", codigo: "ET", emoji: "🇪🇹" },
  { nombre: "Filipinas", codigo: "PH", emoji: "🇵🇭" },
  { nombre: "Finlandia", codigo: "FI", emoji: "🇫🇮" },
  { nombre: "Fiyi", codigo: "FJ", emoji: "🇫🇯" },
  { nombre: "Francia", codigo: "FR", emoji: "🇫🇷" },
  { nombre: "Gabón", codigo: "GA", emoji: "🇬🇦" },
  { nombre: "Gambia", codigo: "GM", emoji: "🇬🇲" },
  { nombre: "Georgia", codigo: "GE", emoji: "🇬🇪" },
  { nombre: "Ghana", codigo: "GH", emoji: "🇬🇭" },
  { nombre: "Granada", codigo: "GD", emoji: "🇬🇩" },
  { nombre: "Grecia", codigo: "GR", emoji: "🇬🇷" },
  { nombre: "Guatemala", codigo: "GT", emoji: "🇬🇹" },
  { nombre: "Guyana", codigo: "GY", emoji: "🇬🇾" },
  { nombre: "Guinea", codigo: "GN", emoji: "🇬🇳" },
  { nombre: "Guinea ecuatorial", codigo: "GQ", emoji: "🇬🇶" },
  { nombre: "Guinea-Bisáu", codigo: "GW", emoji: "🇬🇼" },
  { nombre: "Haití", codigo: "HT", emoji: "🇭🇹" },
  { nombre: "Honduras", codigo: "HN", emoji: "🇭🇳" },
  { nombre: "Hungría", codigo: "HU", emoji: "🇭🇺" },
  { nombre: "India", codigo: "IN", emoji: "🇮🇳" },
  { nombre: "Indonesia", codigo: "ID", emoji: "🇮🇩" },
  { nombre: "Irak", codigo: "IQ", emoji: "🇮🇶" },
  { nombre: "Irán", codigo: "IR", emoji: "🇮🇷" },
  { nombre: "Irlanda", codigo: "IE", emoji: "🇮🇪" },
  { nombre: "Islandia", codigo: "IS", emoji: "🇮🇸" },
  { nombre: "Islas Marshall", codigo: "MH", emoji: "🇲🇭" },
  { nombre: "Islas Salomón", codigo: "SB", emoji: "🇸🇧" },
  { nombre: "Israel", codigo: "IL", emoji: "🇮🇱" },
  { nombre: "Italia", codigo: "IT", emoji: "🇮🇹" },
  { nombre: "Jamaica", codigo: "JM", emoji: "🇯🇲" },
  { nombre: "Japón", codigo: "JP", emoji: "🇯🇵" },
  { nombre: "Jordania", codigo: "JO", emoji: "🇯🇴" },
  { nombre: "Kazajistán", codigo: "KZ", emoji: "🇰🇿" },
  { nombre: "Kenia", codigo: "KE", emoji: "🇰🇪" },
  { nombre: "Kirguistán", codigo: "KG", emoji: "🇰🇬" },
  { nombre: "Kiribati", codigo: "KI", emoji: "🇰🇮" },
  { nombre: "Kuwait", codigo: "KW", emoji: "🇰🇼" },
  { nombre: "Laos", codigo: "LA", emoji: "🇱🇦" },
  { nombre: "Lesoto", codigo: "LS", emoji: "🇱🇸" },
  { nombre: "Letonia", codigo: "LV", emoji: "🇱🇻" },
  { nombre: "Líbano", codigo: "LB", emoji: "🇱🇧" },
  { nombre: "Liberia", codigo: "LR", emoji: "🇱🇷" },
  { nombre: "Libia", codigo: "LY", emoji: "🇱🇾" },
  { nombre: "Liechtenstein", codigo: "LI", emoji: "🇱🇮" },
  { nombre: "Lituania", codigo: "LT", emoji: "🇱🇹" },
  { nombre: "Luxemburgo", codigo: "LU", emoji: "🇱🇺" },
  { nombre: "Madagascar", codigo: "MG", emoji: "🇲🇬" },
  { nombre: "Malasia", codigo: "MY", emoji: "🇲🇾" },
  { nombre: "Malaui", codigo: "MW", emoji: "🇲🇼" },
  { nombre: "Maldivas", codigo: "MV", emoji: "🇲🇻" },
  { nombre: "Malí", codigo: "ML", emoji: "🇲🇱" },
  { nombre: "Malta", codigo: "MT", emoji: "🇲🇹" },
  { nombre: "Marruecos", codigo: "MA", emoji: "🇲🇦" },
  { nombre: "Mauricio", codigo: "MU", emoji: "🇲🇺" },
  { nombre: "Mauritania", codigo: "MR", emoji: "🇲🇷" },
  { nombre: "México", codigo: "MX", emoji: "🇲🇽" },
  { nombre: "Micronesia", codigo: "FM", emoji: "🇫🇲" },
  { nombre: "Moldavia", codigo: "MD", emoji: "🇲🇩" },
  { nombre: "Mónaco", codigo: "MC", emoji: "🇲🇨" },
  { nombre: "Mongolia", codigo: "MN", emoji: "🇲🇳" },
  { nombre: "Montenegro", codigo: "ME", emoji: "🇲🇪" },
  { nombre: "Mozambique", codigo: "MZ", emoji: "🇲🇿" },
  { nombre: "Namibia", codigo: "NA", emoji: "🇳🇦" },
  { nombre: "Nauru", codigo: "NR", emoji: "🇳🇷" },
  { nombre: "Nepal", codigo: "NP", emoji: "🇳🇵" },
  { nombre: "Nicaragua", codigo: "NI", emoji: "🇳🇮" },
  { nombre: "Níger", codigo: "NE", emoji: "🇳🇪" },
  { nombre: "Nigeria", codigo: "NG", emoji: "🇳🇬" },
  { nombre: "Noruega", codigo: "NO", emoji: "🇳🇴" },
  { nombre: "Nueva Zelanda", codigo: "NZ", emoji: "🇳🇿" },
  { nombre: "Omán", codigo: "OM", emoji: "🇴🇲" },
  { nombre: "Países Bajos", codigo: "NL", emoji: "🇳🇱" },
  { nombre: "Pakistán", codigo: "PK", emoji: "🇵🇰" },
  { nombre: "Palaos", codigo: "PW", emoji: "🇵🇼" },
  { nombre: "Palestina", codigo: "PS", emoji: "🇵🇸" },
  { nombre: "Panamá", codigo: "PA", emoji: "🇵🇦" },
  { nombre: "Papúa Nueva Guinea", codigo: "PG", emoji: "🇵🇬" },
  { nombre: "Paraguay", codigo: "PY", emoji: "🇵🇾" },
  { nombre: "Perú", codigo: "PE", emoji: "🇵🇪" },
  { nombre: "Polonia", codigo: "PL", emoji: "🇵🇱" },
  { nombre: "Portugal", codigo: "PT", emoji: "🇵🇹" },
  { nombre: "Reino Unido", codigo: "GB", emoji: "🇬🇧" },
  { nombre: "República Centroafricana", codigo: "CF", emoji: "🇨🇫" },
  { nombre: "República Checa", codigo: "CZ", emoji: "🇨🇿" },
  { nombre: "República del Congo", codigo: "CG", emoji: "🇨🇬" },
  { nombre: "República Democrática del Congo", codigo: "CD", emoji: "🇨🇩" },
  { nombre: "República Dominicana", codigo: "DO", emoji: "🇩🇴" },
  { nombre: "Ruanda", codigo: "RW", emoji: "🇷🇼" },
  { nombre: "Rumanía", codigo: "RO", emoji: "🇷🇴" },
  { nombre: "Rusia", codigo: "RU", emoji: "🇷🇺" },
  { nombre: "Samoa", codigo: "WS", emoji: "🇼🇸" },
  { nombre: "San Cristóbal y Nieves", codigo: "KN", emoji: "🇰🇳" },
  { nombre: "San Marino", codigo: "SM", emoji: "🇸🇲" },
  { nombre: "San Vicente y las Granadinas", codigo: "VC", emoji: "🇻🇨" },
  { nombre: "Santa Lucía", codigo: "LC", emoji: "🇱🇨" },
  { nombre: "Santo Tomé y Príncipe", codigo: "ST", emoji: "🇸🇹" },
  { nombre: "Senegal", codigo: "SN", emoji: "🇸🇳" },
  { nombre: "Serbia", codigo: "RS", emoji: "🇷🇸" },
  { nombre: "Seychelles", codigo: "SC", emoji: "🇸🇨" },
  { nombre: "Sierra Leona", codigo: "SL", emoji: "🇸🇱" },
  { nombre: "Singapur", codigo: "SG", emoji: "🇸🇬" },
  { nombre: "Siria", codigo: "SY", emoji: "🇸🇾" },
  { nombre: "Somalia", codigo: "SO", emoji: "🇸🇴" },
  { nombre: "Sri Lanka", codigo: "LK", emoji: "🇱🇰" },
  { nombre: "Sudáfrica", codigo: "ZA", emoji: "🇿🇦" },
  { nombre: "Sudán", codigo: "SD", emoji: "🇸🇩" },
  { nombre: "Sudán del Sur", codigo: "SS", emoji: "🇸🇸" },
  { nombre: "Suecia", codigo: "SE", emoji: "🇸🇪" },
  { nombre: "Suiza", codigo: "CH", emoji: "🇨🇭" },
  { nombre: "Surinam", codigo: "SR", emoji: "🇸🇷" },
  { nombre: "Tailandia", codigo: "TH", emoji: "🇹🇭" },
  { nombre: "Tanzania", codigo: "TZ", emoji: "🇹🇿" },
  { nombre: "Tayikistán", codigo: "TJ", emoji: "🇹🇯" },
  { nombre: "Timor Oriental", codigo: "TL", emoji: "🇹🇱" },
  { nombre: "Togo", codigo: "TG", emoji: "🇹🇬" },
  { nombre: "Tonga", codigo: "TO", emoji: "🇹🇴" },
  { nombre: "Trinidad y Tobago", codigo: "TT", emoji: "🇹🇹" },
  { nombre: "Túnez", codigo: "TN", emoji: "🇹🇳" },
  { nombre: "Turkmenistán", codigo: "TM", emoji: "🇹🇲" },
  { nombre: "Turquía", codigo: "TR", emoji: "🇹🇷" },
  { nombre: "Tuvalu", codigo: "TV", emoji: "🇹🇻" },
  { nombre: "Ucrania", codigo: "UA", emoji: "🇺🇦" },
  { nombre: "Uganda", codigo: "UG", emoji: "🇺🇬" },
  { nombre: "Uruguay", codigo: "UY", emoji: "🇺🇾" },
  { nombre: "Uzbekistán", codigo: "UZ", emoji: "🇺🇿" },
  { nombre: "Vanuatu", codigo: "VU", emoji: "🇻🇺" },
  { nombre: "Venezuela", codigo: "VE", emoji: "🇻🇪" },
  { nombre: "Vietnam", codigo: "VN", emoji: "🇻🇳" },
  { nombre: "Yemen", codigo: "YE", emoji: "🇾🇪" },
  { nombre: "Yibuti", codigo: "DJ", emoji: "🇩🇯" },
  { nombre: "Zambia", codigo: "ZM", emoji: "🇿🇲" },
  { nombre: "Zimbabue", codigo: "ZW", emoji: "🇿🇼" },
];

// Listado SOLO para el campo de teléfono en fidelización (todos los países)
export const codigosTelefonicos = [
  { nombre: "Afganistán", emoji: "🇦🇫", codigo: "+93" },
  { nombre: "Albania", emoji: "🇦🇱", codigo: "+355" },
  { nombre: "Alemania", emoji: "🇩🇪", codigo: "+49" },
  { nombre: "Andorra", emoji: "🇦🇩", codigo: "+376" },
  { nombre: "Angola", emoji: "🇦🇴", codigo: "+244" },
  { nombre: "Antigua y Barbuda", emoji: "🇦🇬", codigo: "+1-268" },
  { nombre: "Arabia Saudita", emoji: "🇸🇦", codigo: "+966" },
  { nombre: "Argelia", emoji: "🇩🇿", codigo: "+213" },
  { nombre: "Argentina", emoji: "🇦🇷", codigo: "+54" },
  { nombre: "Armenia", emoji: "🇦🇲", codigo: "+374" },
  { nombre: "Australia", emoji: "🇦🇺", codigo: "+61" },
  { nombre: "Austria", emoji: "🇦🇹", codigo: "+43" },
  { nombre: "Azerbaiyán", emoji: "🇦🇿", codigo: "+994" },
  { nombre: "Bahamas", emoji: "🇧🇸", codigo: "+1-242" },
  { nombre: "Bangladés", emoji: "🇧🇩", codigo: "+880" },
  { nombre: "Barbados", emoji: "🇧🇧", codigo: "+1-246" },
  { nombre: "Baréin", emoji: "🇧🇭", codigo: "+973" },
  { nombre: "Bélgica", emoji: "🇧🇪", codigo: "+32" },
  { nombre: "Belice", emoji: "🇧🇿", codigo: "+501" },
  { nombre: "Benín", emoji: "🇧🇯", codigo: "+229" },
  { nombre: "Bielorrusia", emoji: "🇧🇾", codigo: "+375" },
  { nombre: "Birmania", emoji: "🇲🇲", codigo: "+95" },
  { nombre: "Bolivia", emoji: "🇧🇴", codigo: "+591" },
  { nombre: "Bosnia y Herzegovina", emoji: "🇧🇦", codigo: "+387" },
  { nombre: "Botsuana", emoji: "🇧🇼", codigo: "+267" },
  { nombre: "Brasil", emoji: "🇧🇷", codigo: "+55" },
  { nombre: "Brunéi", emoji: "🇧🇳", codigo: "+673" },
  { nombre: "Bulgaria", emoji: "🇧🇬", codigo: "+359" },
  { nombre: "Burkina Faso", emoji: "🇧🇫", codigo: "+226" },
  { nombre: "Burundi", emoji: "🇧🇮", codigo: "+257" },
  { nombre: "Bután", emoji: "🇧🇹", codigo: "+975" },
  { nombre: "Cabo Verde", emoji: "🇨🇻", codigo: "+238" },
  { nombre: "Camboya", emoji: "🇰🇭", codigo: "+855" },
  { nombre: "Camerún", emoji: "🇨🇲", codigo: "+237" },
  { nombre: "Canadá", emoji: "🇨🇦", codigo: "+1" },
  { nombre: "Catar", emoji: "🇶🇦", codigo: "+974" },
  { nombre: "Chad", emoji: "🇹🇩", codigo: "+235" },
  { nombre: "Chile", emoji: "🇨🇱", codigo: "+56" },
  { nombre: "China", emoji: "🇨🇳", codigo: "+86" },
  { nombre: "Chipre", emoji: "🇨🇾", codigo: "+357" },
  { nombre: "Ciudad del Vaticano", emoji: "🇻🇦", codigo: "+39-06" },
  { nombre: "Colombia", emoji: "🇨🇴", codigo: "+57" },
  { nombre: "Comoras", emoji: "🇰🇲", codigo: "+269" },
  { nombre: "Corea del Norte", emoji: "🇰🇵", codigo: "+850" },
  { nombre: "Corea del Sur", emoji: "🇰🇷", codigo: "+82" },
  { nombre: "Costa de Marfil", emoji: "🇨🇮", codigo: "+225" },
  { nombre: "Costa Rica", emoji: "🇨🇷", codigo: "+506" },
  { nombre: "Croacia", emoji: "🇭🇷", codigo: "+385" },
  { nombre: "Cuba", emoji: "🇨🇺", codigo: "+53" },
  { nombre: "Dinamarca", emoji: "🇩🇰", codigo: "+45" },
  { nombre: "Dominica", emoji: "🇩🇲", codigo: "+1-767" },
  { nombre: "Ecuador", emoji: "🇪🇨", codigo: "+593" },
  { nombre: "Egipto", emoji: "🇪🇬", codigo: "+20" },
  { nombre: "El Salvador", emoji: "🇸🇻", codigo: "+503" },
  { nombre: "Emiratos Árabes Unidos", emoji: "🇦🇪", codigo: "+971" },
  { nombre: "Eritrea", emoji: "🇪🇷", codigo: "+291" },
  { nombre: "Eslovaquia", emoji: "🇸🇰", codigo: "+421" },
  { nombre: "Eslovenia", emoji: "🇸🇮", codigo: "+386" },
  { nombre: "España", emoji: "🇪🇸", codigo: "+34" },
  { nombre: "Estados Unidos", emoji: "🇺🇸", codigo: "+1" },
  { nombre: "Estonia", emoji: "🇪🇪", codigo: "+372" },
  { nombre: "Esuatini", emoji: "🇸🇿", codigo: "+268" },
  { nombre: "Etiopía", emoji: "🇪🇹", codigo: "+251" },
  { nombre: "Filipinas", emoji: "🇵🇭", codigo: "+63" },
  { nombre: "Finlandia", emoji: "🇫🇮", codigo: "+358" },
  { nombre: "Fiyi", emoji: "🇫🇯", codigo: "+679" },
  { nombre: "Francia", emoji: "🇫🇷", codigo: "+33" },
  { nombre: "Gabón", emoji: "🇬🇦", codigo: "+241" },
  { nombre: "Gambia", emoji: "🇬🇲", codigo: "+220" },
  { nombre: "Georgia", emoji: "🇬🇪", codigo: "+995" },
  { nombre: "Ghana", emoji: "🇬🇭", codigo: "+233" },
  { nombre: "Granada", emoji: "🇬🇩", codigo: "+1-473" },
  { nombre: "Grecia", emoji: "🇬🇷", codigo: "+30" },
  { nombre: "Guatemala", emoji: "🇬🇹", codigo: "+502" },
  { nombre: "Guyana", emoji: "🇬🇾", codigo: "+592" },
  { nombre: "Guinea", emoji: "🇬🇳", codigo: "+224" },
  { nombre: "Guinea ecuatorial", emoji: "🇬🇶", codigo: "+240" },
  { nombre: "Guinea-Bisáu", emoji: "🇬🇼", codigo: "+245" },
  { nombre: "Haití", emoji: "🇭🇹", codigo: "+509" },
  { nombre: "Honduras", emoji: "🇭🇳", codigo: "+504" },
  { nombre: "Hungría", emoji: "🇭🇺", codigo: "+36" },
  { nombre: "India", emoji: "🇮🇳", codigo: "+91" },
  { nombre: "Indonesia", emoji: "🇮🇩", codigo: "+62" },
  { nombre: "Irak", emoji: "🇮🇶", codigo: "+964" },
  { nombre: "Irán", emoji: "🇮🇷", codigo: "+98" },
  { nombre: "Irlanda", emoji: "🇮🇪", codigo: "+353" },
  { nombre: "Islandia", emoji: "🇮🇸", codigo: "+354" },
  { nombre: "Islas Marshall", emoji: "🇲🇭", codigo: "+692" },
  { nombre: "Islas Salomón", emoji: "🇸🇧", codigo: "+677" },
  { nombre: "Israel", emoji: "🇮🇱", codigo: "+972" },
  { nombre: "Italia", emoji: "🇮🇹", codigo: "+39" },
  { nombre: "Jamaica", emoji: "🇯🇲", codigo: "+1-876" },
  { nombre: "Japón", emoji: "🇯🇵", codigo: "+81" },
  { nombre: "Jordania", emoji: "🇯🇴", codigo: "+962" },
  { nombre: "Kazajistán", emoji: "🇰🇿", codigo: "+7" },
  { nombre: "Kenia", emoji: "🇰🇪", codigo: "+254" },
  { nombre: "Kirguistán", emoji: "🇰🇬", codigo: "+996" },
  { nombre: "Kiribati", emoji: "🇰🇮", codigo: "+686" },
  { nombre: "Kuwait", emoji: "🇰🇼", codigo: "+965" },
  { nombre: "Laos", emoji: "🇱🇦", codigo: "+856" },
  { nombre: "Lesoto", emoji: "🇱🇸", codigo: "+266" },
  { nombre: "Letonia", emoji: "🇱🇻", codigo: "+371" },
  { nombre: "Líbano", emoji: "🇱🇧", codigo: "+961" },
  { nombre: "Liberia", emoji: "🇱🇷", codigo: "+231" },
  { nombre: "Libia", emoji: "🇱🇾", codigo: "+218" },
  { nombre: "Liechtenstein", emoji: "🇱🇮", codigo: "+423" },
  { nombre: "Lituania", emoji: "🇱🇹", codigo: "+370" },
  { nombre: "Luxemburgo", emoji: "🇱🇺", codigo: "+352" },
  { nombre: "Madagascar", emoji: "🇲🇬", codigo: "+261" },
  { nombre: "Malasia", emoji: "🇲🇾", codigo: "+60" },
  { nombre: "Malaui", emoji: "🇲🇼", codigo: "+265" },
  { nombre: "Maldivas", emoji: "🇲🇻", codigo: "+960" },
  { nombre: "Malí", emoji: "🇲🇱", codigo: "+223" },
  { nombre: "Malta", emoji: "🇲🇹", codigo: "+356" },
  { nombre: "Marruecos", emoji: "🇲🇦", codigo: "+212" },
  { nombre: "Mauricio", emoji: "🇲🇺", codigo: "+230" },
  { nombre: "Mauritania", emoji: "🇲🇷", codigo: "+222" },
  { nombre: "México", emoji: "🇲🇽", codigo: "+52" },
  { nombre: "Micronesia", emoji: "🇫🇲", codigo: "+691" },
  { nombre: "Moldavia", emoji: "🇲🇩", codigo: "+373" },
  { nombre: "Mónaco", emoji: "🇲🇨", codigo: "+377" },
  { nombre: "Mongolia", emoji: "🇲🇳", codigo: "+976" },
  { nombre: "Montenegro", emoji: "🇲🇪", codigo: "+382" },
  { nombre: "Mozambique", emoji: "🇲🇿", codigo: "+258" },
  { nombre: "Namibia", emoji: "🇳🇦", codigo: "+264" },
  { nombre: "Nauru", emoji: "🇳🇷", codigo: "+674" },
  { nombre: "Nepal", emoji: "🇳🇵", codigo: "+977" },
  { nombre: "Nicaragua", emoji: "🇳🇮", codigo: "+505" },
  { nombre: "Níger", emoji: "🇳🇪", codigo: "+227" },
  { nombre: "Nigeria", emoji: "🇳🇬", codigo: "+234" },
  { nombre: "Noruega", emoji: "🇳🇴", codigo: "+47" },
  { nombre: "Nueva Zelanda", emoji: "🇳🇿", codigo: "+64" },
  { nombre: "Omán", emoji: "🇴🇲", codigo: "+968" },
  { nombre: "Países Bajos", emoji: "🇳🇱", codigo: "+31" },
  { nombre: "Pakistán", emoji: "🇵🇰", codigo: "+92" },
  { nombre: "Palaos", emoji: "🇵🇼", codigo: "+680" },
  { nombre: "Palestina", emoji: "🇵🇸", codigo: "+970" },
  { nombre: "Panamá", emoji: "🇵🇦", codigo: "+507" },
  { nombre: "Papúa Nueva Guinea", emoji: "🇵🇬", codigo: "+675" },
  { nombre: "Paraguay", emoji: "🇵🇾", codigo: "+595" },
  { nombre: "Perú", emoji: "🇵🇪", codigo: "+51" },
  { nombre: "Polonia", emoji: "🇵🇱", codigo: "+48" },
  { nombre: "Portugal", emoji: "🇵🇹", codigo: "+351" },
  { nombre: "Reino Unido", emoji: "🇬🇧", codigo: "+44" },
  { nombre: "República Centroafricana", emoji: "🇨🇫", codigo: "+236" },
  { nombre: "República Checa", emoji: "🇨🇿", codigo: "+420" },
  { nombre: "República del Congo", emoji: "🇨🇬", codigo: "+242" },
  { nombre: "República Democrática del Congo", emoji: "🇨🇩", codigo: "+243" },
  { nombre: "República Dominicana", emoji: "🇩🇴", codigo: "+1-809" },
  { nombre: "Ruanda", emoji: "🇷🇼", codigo: "+250" },
  { nombre: "Rumanía", emoji: "🇷🇴", codigo: "+40" },
  { nombre: "Rusia", emoji: "🇷🇺", codigo: "+7" },
  { nombre: "Samoa", emoji: "🇼🇸", codigo: "+685" },
  { nombre: "San Cristóbal y Nieves", emoji: "🇰🇳", codigo: "+1-869" },
  { nombre: "San Marino", emoji: "🇸🇲", codigo: "+378" },
  { nombre: "San Vicente y las Granadinas", emoji: "🇻🇨", codigo: "+1-784" },
  { nombre: "Santa Lucía", emoji: "🇱🇨", codigo: "+1-758" },
  { nombre: "Santo Tomé y Príncipe", emoji: "🇸🇹", codigo: "+239" },
  { nombre: "Senegal", emoji: "🇸🇳", codigo: "+221" },
  { nombre: "Serbia", emoji: "🇷🇸", codigo: "+381" },
  { nombre: "Seychelles", emoji: "🇸🇨", codigo: "+248" },
  { nombre: "Sierra Leona", emoji: "🇸🇱", codigo: "+232" },
  { nombre: "Singapur", emoji: "🇸🇬", codigo: "+65" },
  { nombre: "Siria", emoji: "🇸🇾", codigo: "+963" },
  { nombre: "Somalia", emoji: "🇸🇴", codigo: "+252" },
  { nombre: "Sri Lanka", emoji: "🇱🇰", codigo: "+94" },
  { nombre: "Sudáfrica", emoji: "🇿🇦", codigo: "+27" },
  { nombre: "Sudán", emoji: "🇸🇩", codigo: "+249" },
  { nombre: "Sudán del Sur", emoji: "🇸🇸", codigo: "+211" },
  { nombre: "Suecia", emoji: "🇸🇪", codigo: "+46" },
  { nombre: "Suiza", emoji: "🇨🇭", codigo: "+41" },
  { nombre: "Surinam", emoji: "🇸🇷", codigo: "+597" },
  { nombre: "Tailandia", emoji: "🇹🇭", codigo: "+66" },
  { nombre: "Tanzania", emoji: "🇹🇿", codigo: "+255" },
  { nombre: "Tayikistán", emoji: "🇹🇯", codigo: "+992" },
  { nombre: "Timor Oriental", emoji: "🇹🇱", codigo: "+670" },
  { nombre: "Togo", emoji: "🇹🇬", codigo: "+228" },
  { nombre: "Tonga", emoji: "🇹🇴", codigo: "+676" },
  { nombre: "Trinidad y Tobago", emoji: "🇹🇹", codigo: "+1-868" },
  { nombre: "Túnez", emoji: "🇹🇳", codigo: "+216" },
  { nombre: "Turkmenistán", emoji: "🇹🇲", codigo: "+993" },
  { nombre: "Turquía", emoji: "🇹🇷", codigo: "+90" },
  { nombre: "Tuvalu", emoji: "🇹🇻", codigo: "+688" },
  { nombre: "Ucrania", emoji: "🇺🇦", codigo: "+380" },
  { nombre: "Uganda", emoji: "🇺🇬", codigo: "+256" },
  { nombre: "Uruguay", emoji: "🇺🇾", codigo: "+598" },
  { nombre: "Uzbekistán", emoji: "🇺🇿", codigo: "+998" },
  { nombre: "Vanuatu", emoji: "🇻🇺", codigo: "+678" },
  { nombre: "Venezuela", emoji: "🇻🇪", codigo: "+58" },
  { nombre: "Vietnam", emoji: "🇻🇳", codigo: "+84" },
  { nombre: "Yemen", emoji: "🇾🇪", codigo: "+967" },
  { nombre: "Yibuti", emoji: "🇩🇯", codigo: "+253" },
  { nombre: "Zambia", emoji: "🇿🇲", codigo: "+260" },
  { nombre: "Zimbabue", emoji: "🇿🇼", codigo: "+263" },
]; 