// Listado de divisas del mundo para el selector de moneda en fidelización
// Formato: nombre, código, símbolo, emoji (bandera)
export interface Currency {
  nombre: string;
  codigo: string;
  simbolo: string;
  emoji: string;
  tickBase?: number;
}

export const currencies: Currency[] = [
  { nombre: 'Dólar estadounidense', codigo: 'USD', simbolo: '$', emoji: '🇺🇸', tickBase: 10 },
  { nombre: 'Euro', codigo: 'EUR', simbolo: '€', emoji: '🇪🇺', tickBase: 10 },
  { nombre: 'Peso mexicano', codigo: 'MXN', simbolo: '$', emoji: '🇲🇽', tickBase: 100 },
  { nombre: 'Peso colombiano', codigo: 'COP', simbolo: '$', emoji: '🇨🇴', tickBase: 1000 },
  { nombre: 'Peso argentino', codigo: 'ARS', simbolo: '$', emoji: '🇦🇷', tickBase: 1000 },
  { nombre: 'Real brasileño', codigo: 'BRL', simbolo: 'R$', emoji: '🇧🇷', tickBase: 100 },
  { nombre: 'Libra esterlina', codigo: 'GBP', simbolo: '£', emoji: '🇬🇧', tickBase: 10 },
  { nombre: 'Yen japonés', codigo: 'JPY', simbolo: '¥', emoji: '🇯🇵', tickBase: 1000 },
  { nombre: 'Franco suizo', codigo: 'CHF', simbolo: 'Fr', emoji: '🇨🇭', tickBase: 10 },
  { nombre: 'Dólar canadiense', codigo: 'CAD', simbolo: '$', emoji: '🇨🇦', tickBase: 10 },
  { nombre: 'Sol peruano', codigo: 'PEN', simbolo: 'S/', emoji: '🇵🇪', tickBase: 10 },
  { nombre: 'Peso chileno', codigo: 'CLP', simbolo: '$', emoji: '🇨🇱', tickBase: 1000 },
  { nombre: 'Bolívar venezolano', codigo: 'VES', simbolo: 'Bs.', emoji: '🇻🇪', tickBase: 100 },
  { nombre: 'Peso uruguayo', codigo: 'UYU', simbolo: '$', emoji: '🇺🇾', tickBase: 100 },
  { nombre: 'Guaraní paraguayo', codigo: 'PYG', simbolo: '₲', emoji: '🇵🇾', tickBase: 10000 },
  { nombre: 'Dólar australiano', codigo: 'AUD', simbolo: '$', emoji: '🇦🇺', tickBase: 10 },
  { nombre: 'Yuan chino', codigo: 'CNY', simbolo: '¥', emoji: '🇨🇳', tickBase: 10 },
  { nombre: 'Rublo ruso', codigo: 'RUB', simbolo: '₽', emoji: '🇷🇺', tickBase: 100 },
  { nombre: 'Rand sudafricano', codigo: 'ZAR', simbolo: 'R', emoji: '🇿🇦', tickBase: 100 },
  { nombre: 'Lira turca', codigo: 'TRY', simbolo: '₺', emoji: '🇹🇷', tickBase: 100 },
  { nombre: 'Peso dominicano', codigo: 'DOP', simbolo: 'RD$', emoji: '🇩🇴', tickBase: 100 },
  { nombre: 'Quetzal guatemalteco', codigo: 'GTQ', simbolo: 'Q', emoji: '🇬🇹', tickBase: 10 },
  { nombre: 'Córdoba nicaragüense', codigo: 'NIO', simbolo: 'C$', emoji: '🇳🇮', tickBase: 100 },
  { nombre: 'Lempira hondureño', codigo: 'HNL', simbolo: 'L', emoji: '🇭🇳', tickBase: 100 },
  { nombre: 'Balboa panameño', codigo: 'PAB', simbolo: 'B/.', emoji: '🇵🇦', tickBase: 10 },
  { nombre: 'Dólar de Singapur', codigo: 'SGD', simbolo: '$', emoji: '🇸🇬', tickBase: 10 },
  { nombre: 'Dólar neozelandés', codigo: 'NZD', simbolo: '$', emoji: '🇳🇿', tickBase: 10 },
  { nombre: 'Peso filipino', codigo: 'PHP', simbolo: '₱', emoji: '🇵🇭', tickBase: 100 },
  { nombre: 'Dirham marroquí', codigo: 'MAD', simbolo: 'د.م.', emoji: '🇲🇦', tickBase: 100 },
  { nombre: 'Shekel israelí', codigo: 'ILS', simbolo: '₪', emoji: '🇮🇱', tickBase: 10 },
  { nombre: 'Dinar argelino', codigo: 'DZD', simbolo: 'دج', emoji: '🇩🇿', tickBase: 100 },
  { nombre: 'Dinar tunecino', codigo: 'TND', simbolo: 'د.ت', emoji: '🇹🇳', tickBase: 10 },
  { nombre: 'Dinar jordano', codigo: 'JOD', simbolo: 'د.ا', emoji: '🇯🇴', tickBase: 10 },
  { nombre: 'Dinar kuwaití', codigo: 'KWD', simbolo: 'د.ك', emoji: '🇰🇼', tickBase: 10 },
  { nombre: 'Dinar bahreiní', codigo: 'BHD', simbolo: 'ب.د', emoji: '🇧🇭', tickBase: 10 },
  { nombre: 'Dinar iraquí', codigo: 'IQD', simbolo: 'ع.د', emoji: '🇮🇶', tickBase: 1000 },
  { nombre: 'Riyal saudí', codigo: 'SAR', simbolo: 'ر.س', emoji: '🇸🇦', tickBase: 10 },
  { nombre: 'Riyal catarí', codigo: 'QAR', simbolo: 'ر.ق', emoji: '🇶🇦', tickBase: 10 },
  { nombre: 'Riyal omaní', codigo: 'OMR', simbolo: 'ر.ع.', emoji: '🇴🇲', tickBase: 10 },
  { nombre: 'Riyal yemení', codigo: 'YER', simbolo: '﷼', emoji: '🇾🇪', tickBase: 100 },
  { nombre: 'Rupia india', codigo: 'INR', simbolo: '₹', emoji: '🇮🇳', tickBase: 100 },
  { nombre: 'Rupia indonesia', codigo: 'IDR', simbolo: 'Rp', emoji: '🇮🇩', tickBase: 10000 },
  { nombre: 'Rupia pakistaní', codigo: 'PKR', simbolo: '₨', emoji: '🇵🇰', tickBase: 100 },
  { nombre: 'Rupia de Sri Lanka', codigo: 'LKR', simbolo: '₨', emoji: '🇱🇰', tickBase: 100 },
  { nombre: 'Rupia de Seychelles', codigo: 'SCR', simbolo: '₨', emoji: '🇸🇨', tickBase: 100 },
  { nombre: 'Rupia de Mauricio', codigo: 'MUR', simbolo: '₨', emoji: '🇲🇺', tickBase: 100 },
  { nombre: 'Rupia de Maldivas', codigo: 'MVR', simbolo: 'Rf', emoji: '🇲🇻', tickBase: 100 },
  { nombre: 'Rupia nepalí', codigo: 'NPR', simbolo: '₨', emoji: '🇳🇵', tickBase: 100 },
  { nombre: 'Won surcoreano', codigo: 'KRW', simbolo: '₩', emoji: '🇰🇷', tickBase: 10000 },
  { nombre: 'Ringgit malayo', codigo: 'MYR', simbolo: 'RM', emoji: '🇲🇾', tickBase: 10 },
  { nombre: 'Baht tailandés', codigo: 'THB', simbolo: '฿', emoji: '🇹🇭', tickBase: 100 },
  { nombre: 'Dólar de Hong Kong', codigo: 'HKD', simbolo: '$', emoji: '🇭🇰', tickBase: 10 },
  { nombre: 'Dólar taiwanés', codigo: 'TWD', simbolo: 'NT$', emoji: '🇹🇼', tickBase: 100 },
  { nombre: 'Dólar jamaicano', codigo: 'JMD', simbolo: 'J$', emoji: '🇯🇲', tickBase: 100 },
  { nombre: 'Dólar bahameño', codigo: 'BSD', simbolo: 'B$', emoji: '🇧🇸', tickBase: 10 },
  { nombre: 'Dólar de Belice', codigo: 'BZD', simbolo: 'BZ$', emoji: '🇧🇿', tickBase: 10 },
  { nombre: 'Dólar bermudeño', codigo: 'BMD', simbolo: '$', emoji: '🇧🇲', tickBase: 10 },
  { nombre: 'Dólar barbadense', codigo: 'BBD', simbolo: 'Bds$', emoji: '🇧🇧', tickBase: 10 },
  { nombre: 'Dólar de Trinidad y Tobago', codigo: 'TTD', simbolo: 'TT$', emoji: '🇹🇹', tickBase: 10 },
  { nombre: 'Dólar guyanés', codigo: 'GYD', simbolo: '$', emoji: '🇬🇾', tickBase: 100 },
  { nombre: 'Dólar surinamés', codigo: 'SRD', simbolo: '$', emoji: '🇸🇷', tickBase: 100 },
  { nombre: 'Dólar de Barbados', codigo: 'BBD', simbolo: 'Bds$', emoji: '🇧🇧', tickBase: 10 },
  { nombre: 'Dólar de Fiyi', codigo: 'FJD', simbolo: '$', emoji: '🇫🇯', tickBase: 10 },
  { nombre: 'Dólar de Islas Salomón', codigo: 'SBD', simbolo: '$', emoji: '🇸🇧', tickBase: 10 },
  { nombre: 'Dólar de Islas Caimán', codigo: 'KYD', simbolo: '$', emoji: '🇰🇾', tickBase: 10 },
  { nombre: 'Dólar de Islas Cook', codigo: 'CKD', simbolo: '$', emoji: '🇨🇰', tickBase: 10 },
  { nombre: 'Dólar de Nueva Zelanda', codigo: 'NZD', simbolo: '$', emoji: '🇳🇿', tickBase: 10 },
  { nombre: 'Dólar de Singapur', codigo: 'SGD', simbolo: '$', emoji: '🇸🇬', tickBase: 10 },
  { nombre: 'Dólar de Brunéi', codigo: 'BND', simbolo: '$', emoji: '🇧🇳', tickBase: 10 },
  { nombre: 'Dólar liberiano', codigo: 'LRD', simbolo: '$', emoji: '🇱🇷', tickBase: 100 },
  { nombre: 'Dólar namibio', codigo: 'NAD', simbolo: '$', emoji: '🇳🇦', tickBase: 100 },
  { nombre: 'Dólar zimbabuense', codigo: 'ZWL', simbolo: '$', emoji: '🇿🇼', tickBase: 1000 },
  // ...puedes agregar más si lo necesitas...
]; 